export const routes = {
  home: "/",
  faq: "/faq",
  catalogue: "/catalogue",
  about: "/about",
  search: "/search",
  cart: "/cart",
  checkout: "/checkout",
  checkoutSuccess: "/checkout/success",
  paymentMethod: "/payment-method",
  statusOrder: "/status-order",
  orderHistory: "/order-history",
  profile: "/profile",
  login: "/login",
  register: "/register",
  admin: {
    overview: "/admin",
    products: "/admin/products",
    categories: "/admin/categories",
    orders: "/admin/orders",
    payments: "/admin/payments",
    vouchers: "/admin/vouchers",
    faqs: "/admin/faqs",
    content: "/admin/content",
    orderStatuses: "/admin/order-statuses",
    reports: "/admin/reports",
    inventory: "/admin/inventory",
  },
  product: (slug: string) => `/product/${slug}`,
} as const;
